packages:
  - packages/*
  - '!packages/effortless-runner'
  - integration

allowBuilds:
  '@effect-ak/aws-sdk': true
  '@parcel/watcher': true
  esbuild: true
  msgpackr-extract: true

catalog:
  '@aws-sdk/client-acm': ^3.993.0
  '@aws-sdk/client-apigatewayv2': ^3.975.0
  '@aws-sdk/client-cloudfront': ^3.989.0
  '@aws-sdk/client-cloudwatch': ^3.1014.0
  '@aws-sdk/client-cloudwatch-logs': ^3.990.0
  '@aws-sdk/client-dynamodb': ^3.975.0
  '@aws-sdk/client-ec2': ^3.1014.0
  '@aws-sdk/client-ecs': ^3.1014.0
  '@aws-sdk/client-iam': ^3.975.0
  '@aws-sdk/client-lambda': ^3.975.0
  '@aws-sdk/client-resource-groups-tagging-api': ^3.975.0
  '@aws-sdk/client-s3': ^3.989.0
  '@aws-sdk/client-sesv2': ^3.994.0
  '@aws-sdk/client-sns': ^3.1014.0
  '@aws-sdk/client-sqs': 3.989.0
  '@aws-sdk/client-ssm': ^3.985.0
  '@aws-sdk/util-dynamodb': ^3.975.0
  '@types/node': 22.19.9
  tsup: ^8.5.1
  type-fest: ^4.22.1
  typescript: ^5.9.3
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4.0.18
  '@modelcontextprotocol/sdk': ^1.29.0
  '@standard-schema/spec': ^1.1.0
  effect: 4.0.0-beta.57
  zod: ^4.3.0
