// Auto-generated by effortless-aws. DO NOT EDIT.
// This file contains all types and runtime needed for the handler.
// Re-run `effortless generate` to regenerate after infra changes.

// ============ Types ============

export type HttpRequest = {
  method: string;
  path: string;
  headers: Record<string, string>;
  query: Record<string, string>;
  body: string | undefined;
  rawBody: string | undefined;
  isBase64Encoded: boolean;
};

export type HttpResponse = {
  status: number;
  body?: unknown;
  headers?: Record<string, string>;
  contentType?: "json" | "html" | "text";
};

export type OkHelper = (body?: unknown, status?: number) => HttpResponse;
export type FailHelper = (message: string, status?: number) => HttpResponse;

// --- Dep clients ---

type TableClient = {
  get(pk: string, sk: string): Promise<Record<string, unknown> | null>;
  put(pk: string, sk: string, data: Record<string, unknown>): Promise<void>;
  query(params: { pk: string; sk?: string; limit?: number }): Promise<Record<string, unknown>[]>;
  delete(pk: string, sk: string): Promise<void>;
};

type BucketClient = {
  get(key: string): Promise<string | null>;
  put(key: string, body: string | Buffer): Promise<void>;
  delete(key: string): Promise<void>;
  getSignedUrl(key: string, expiresIn?: number): Promise<string>;
};

type QueueClient = {
  send(body: unknown, groupId?: string, deduplicationId?: string): Promise<void>;
};

type EmailClient = {
  send(options: { to: string | string[]; subject: string; html?: string; text?: string; from?: string }): Promise<void>;
};

type WorkerClient = {
  send(message: unknown): Promise<void>;
};

export type Deps = {
  db: TableClient;
};

export type HandlerContext = {
  req: HttpRequest;
  ok: OkHelper;
  fail: FailHelper;
  db: Deps["db"];
};

export type Handler = (ctx: HandlerContext) => Promise<HttpResponse>;

// ============ Inlined runtime ============

const ok: OkHelper = (body, status = 200) => ({ status, body });
const fail: FailHelper = (message, status = 400) => ({ status, body: { error: message } });

type LambdaEvent = {
  requestContext?: { http?: { method?: string; path?: string } };
  headers?: Record<string, string>;
  queryStringParameters?: Record<string, string>;
  body?: string;
  isBase64Encoded?: boolean;
  rawPath?: string;
};

type LambdaResponse = {
  statusCode: number;
  headers: Record<string, string>;
  body: string;
};

function parseRequest(event: LambdaEvent): HttpRequest {
  const method = (event.requestContext?.http?.method ?? "GET").toUpperCase();
  const path = event.rawPath ?? event.requestContext?.http?.path ?? "/";
  const headers: Record<string, string> = {};
  if (event.headers) {
    for (const [k, v] of Object.entries(event.headers)) {
      headers[k.toLowerCase()] = v;
    }
  }
  const query = event.queryStringParameters ?? {};
  const rawBody = event.body;
  const isBase64 = event.isBase64Encoded ?? false;
  let body: string | undefined;
  if (rawBody) {
    body = isBase64 ? Buffer.from(rawBody, "base64").toString("utf-8") : rawBody;
  }
  return { method, path, headers, query, body, rawBody, isBase64Encoded: isBase64 };
}

function toLambdaResponse(res: HttpResponse): LambdaResponse {
  const contentType = res.contentType === "html"
    ? "text/html; charset=utf-8"
    : res.contentType === "text"
      ? "text/plain; charset=utf-8"
      : "application/json";
  const isJson = contentType === "application/json";
  return {
    statusCode: res.status,
    headers: { "Content-Type": contentType, ...res.headers },
    body: isJson && res.body !== undefined ? JSON.stringify(res.body) : String(res.body ?? ""),
  };
}


function createTableClient(tableName: string): TableClient {
  const { DynamoDBClient } = require("@aws-sdk/client-dynamodb");
  const { DynamoDBDocumentClient, GetCommand, PutCommand, QueryCommand, DeleteCommand } = require("@aws-sdk/lib-dynamodb");
  const client = DynamoDBDocumentClient.from(new DynamoDBClient({}));
  return {
    async get(pk, sk) {
      const res = await client.send(new GetCommand({ TableName: tableName, Key: { pk, sk } }));
      return (res.Item as Record<string, unknown>) ?? null;
    },
    async put(pk, sk, data) {
      await client.send(new PutCommand({ TableName: tableName, Item: { pk, sk, data } }));
    },
    async query(params) {
      const res = await client.send(new QueryCommand({
        TableName: tableName,
        KeyConditionExpression: params.sk ? "pk = :pk AND sk = :sk" : "pk = :pk",
        ExpressionAttributeValues: { ":pk": params.pk, ...(params.sk ? { ":sk": params.sk } : {}) },
        ...(params.limit ? { Limit: params.limit } : {}),
      }));
      return (res.Items as Record<string, unknown>[]) ?? [];
    },
    async delete(pk, sk) {
      await client.send(new DeleteCommand({ TableName: tableName, Key: { pk, sk } }));
    },
  };
}


function getEnvDep(name: string): string {
  const raw = process.env[`EFF_DEP_${name}`];
  if (!raw) throw new Error(`Missing dependency env var: EFF_DEP_${name}`);
  // Format: "type:resourceName" — extract the resource name
  const colonIdx = raw.indexOf(":");
  return colonIdx >= 0 ? raw.slice(colonIdx + 1) : raw;
}

function resolveDeps(): Deps {
  return {
    db: createTableClient(getEnvDep("db")),
  };
}

export function createHandler(handler: Handler) {
  let deps: Deps | undefined;

  return async (event: LambdaEvent): Promise<LambdaResponse> => {
    if (!deps) deps = resolveDeps(); // lazy init on first invocation

    const req = parseRequest(event);
    const ctx: HandlerContext = { req, ok, fail, ...deps };
    try {
      const response = await handler(ctx);
      return toLambdaResponse(response);
    } catch (error) {
      console.error("Handler error:", error);
      return toLambdaResponse(fail("Internal Server Error", 500));
    }
  };
}
