// Auto-generated by effortless-aws. DO NOT EDIT.
// Re-run `effortless generate` to regenerate after infra changes.

// --- Dep clients ---

type TableClient = {
  get(pk: string, sk: string): Promise<Record<string, unknown> | null>;
  put(pk: string, sk: string, data: Record<string, unknown>): Promise<void>;
  query(params: { pk: string; sk?: string; limit?: number }): Promise<Record<string, unknown>[]>;
  delete(pk: string, sk: string): Promise<void>;
};

export type Deps = {
  orders: TableClient;
};


export type HandlerContext = {
  orders: Deps["orders"];
};

export type Handler = (ctx: HandlerContext) => Promise<void>;

// ============ Inlined runtime ============

type LambdaEvent = Record<string, unknown>;


function createTableClient(tableName: string): TableClient {
  const { DynamoDBClient } = require("@aws-sdk/client-dynamodb");
  const { DynamoDBDocumentClient, GetCommand, PutCommand, QueryCommand, DeleteCommand } = require("@aws-sdk/lib-dynamodb");
  const client = DynamoDBDocumentClient.from(new DynamoDBClient({}));
  return {
    async get(pk, sk) {
      const res = await client.send(new GetCommand({ TableName: tableName, Key: { pk, sk } }));
      return (res.Item as Record<string, unknown>) ?? null;
    },
    async put(pk, sk, data) {
      await client.send(new PutCommand({ TableName: tableName, Item: { pk, sk, data } }));
    },
    async query(params) {
      const res = await client.send(new QueryCommand({
        TableName: tableName,
        KeyConditionExpression: params.sk ? "pk = :pk AND sk = :sk" : "pk = :pk",
        ExpressionAttributeValues: { ":pk": params.pk, ...(params.sk ? { ":sk": params.sk } : {}) },
        ...(params.limit ? { Limit: params.limit } : {}),
      }));
      return (res.Items as Record<string, unknown>[]) ?? [];
    },
    async delete(pk, sk) {
      await client.send(new DeleteCommand({ TableName: tableName, Key: { pk, sk } }));
    },
  };
}

function getEnvDep(name: string): string {
  const raw = process.env[`EFF_DEP_${name}`];
  if (!raw) throw new Error(`Missing dependency env var: EFF_DEP_${name}`);
  const colonIdx = raw.indexOf(":");
  return colonIdx >= 0 ? raw.slice(colonIdx + 1) : raw;
}

function resolveDeps(): Deps {
  return {
    orders: createTableClient(getEnvDep("orders")),
  };
}

export function createHandler(handler: Handler) {
  let deps: Deps | undefined;

  return async (_event: LambdaEvent): Promise<void> => {
    if (!deps) deps = resolveDeps();

    const ctx: HandlerContext = { ...deps };
    try {
      await handler(ctx);
    } catch (error) {
      console.error("Cron handler error:", error);
      throw error;
    }
  };
}
