/**
 * Generates handler.gen.ts for a Bucket event handler — self-contained adapter with
 * all runtime code inlined (zero imports from effortless-aws).
 */

import { generateDepsSection, type GenerateDepsInput } from "./generate-ts-deps";

export type GenerateBucketInput = GenerateDepsInput;

export const generateBucketAdapter = (input: GenerateBucketInput): string => {
  const { deps } = input;
  const hasDeps = Object.keys(deps).length > 0;
  const depsSection = generateDepsSection(deps);

  return `// Auto-generated by effortless-aws. DO NOT EDIT.
// Re-run \`effortless generate\` to regenerate after infra changes.

// ============ Types ============

export type BucketEvent = {
  eventName: "ObjectCreated" | "ObjectRemoved";
  key: string;
  size?: number;
  bucket: string;
};

${depsSection.types}

export type HandlerContext = {
  event: BucketEvent;
${hasDeps ? Object.keys(deps).map(name => `  ${name}: Deps["${name}"];`).join("\n") : ""}
};

export type Handler = (ctx: HandlerContext) => Promise<void>;

// ============ Inlined runtime ============

type S3Event = {
  Records: Array<{
    eventName?: string;
    s3?: {
      bucket?: { name?: string };
      object?: { key?: string; size?: number };
    };
  }>;
};

${depsSection.runtime}
export function createHandler(handler: Handler) {
${hasDeps ? "  let deps: Deps | undefined;\n" : ""}
  return async (event: S3Event): Promise<void> => {
${hasDeps ? "    if (!deps) deps = resolveDeps();\n" : ""}
    for (const record of event.Records) {
      try {
        const eventName = record.eventName?.startsWith("ObjectCreated") ? "ObjectCreated" : "ObjectRemoved";
        const bucketEvent: BucketEvent = {
          eventName: eventName as "ObjectCreated" | "ObjectRemoved",
          key: decodeURIComponent((record.s3?.object?.key ?? "").replace(/\\+/g, " ")),
          size: record.s3?.object?.size,
          bucket: record.s3?.bucket?.name ?? "",
        };
        const ctx: HandlerContext = { event: bucketEvent${hasDeps ? ", ...deps" : ""} };
        await handler(ctx);
      } catch (error) {
        console.error("Bucket handler error:", error);
        throw error;
      }
    }
  };
}
`;
};
