/**
 * Generates handler.gen.ts for an API handler — self-contained adapter with
 * all runtime code inlined (zero imports from effortless-aws).
 */

export type GenerateApiInput = {
  /** Dep names and their handler types (e.g., { db: "table", uploads: "bucket" }) */
  deps: Record<string, string>;
  /** Whether the handler uses streaming */
  stream?: boolean;
};

export const generateApiAdapter = (input: GenerateApiInput): string => {
  const { deps, stream } = input;
  const hasDeps = Object.keys(deps).length > 0;

  const depsTypeEntries = Object.entries(deps).map(([name, type]) => {
    switch (type) {
      case "table": return `  ${name}: TableClient;`;
      case "bucket": return `  ${name}: BucketClient;`;
      case "fifoQueue": return `  ${name}: QueueClient;`;
      case "mailer": return `  ${name}: EmailClient;`;
      case "worker": return `  ${name}: WorkerClient;`;
      default: return `  ${name}: unknown;`;
    }
  });

  return `// Auto-generated by effortless-aws. DO NOT EDIT.
// This file contains all types and runtime needed for the handler.
// Re-run \`effortless generate\` to regenerate after infra changes.

// ============ Types ============

export type HttpRequest = {
  method: string;
  path: string;
  headers: Record<string, string>;
  query: Record<string, string>;
  body: string | undefined;
  rawBody: string | undefined;
  isBase64Encoded: boolean;
};

export type HttpResponse = {
  status: number;
  body?: unknown;
  headers?: Record<string, string>;
  contentType?: "json" | "html" | "text";
};

export type OkHelper = (body?: unknown, status?: number) => HttpResponse;
export type FailHelper = (message: string, status?: number) => HttpResponse;

${hasDeps ? `// --- Dep clients ---

type TableClient = {
  get(pk: string, sk: string): Promise<Record<string, unknown> | null>;
  put(pk: string, sk: string, data: Record<string, unknown>): Promise<void>;
  query(params: { pk: string; sk?: string; limit?: number }): Promise<Record<string, unknown>[]>;
  delete(pk: string, sk: string): Promise<void>;
};

type BucketClient = {
  get(key: string): Promise<string | null>;
  put(key: string, body: string | Buffer): Promise<void>;
  delete(key: string): Promise<void>;
  getSignedUrl(key: string, expiresIn?: number): Promise<string>;
};

type QueueClient = {
  send(body: unknown, groupId?: string, deduplicationId?: string): Promise<void>;
};

type EmailClient = {
  send(options: { to: string | string[]; subject: string; html?: string; text?: string; from?: string }): Promise<void>;
};

type WorkerClient = {
  send(message: unknown): Promise<void>;
};

export type Deps = {
${depsTypeEntries.join("\n")}
};
` : ""}
export type HandlerContext = {
  req: HttpRequest;
  ok: OkHelper;
  fail: FailHelper;
${hasDeps ? Object.entries(deps).map(([name]) => `  ${name}: Deps["${name}"];`).join("\n") : ""}
};

export type Handler = (ctx: HandlerContext) => Promise<HttpResponse>;

// ============ Inlined runtime ============

const ok: OkHelper = (body, status = 200) => ({ status, body });
const fail: FailHelper = (message, status = 400) => ({ status, body: { error: message } });

type LambdaEvent = {
  requestContext?: { http?: { method?: string; path?: string } };
  headers?: Record<string, string>;
  queryStringParameters?: Record<string, string>;
  body?: string;
  isBase64Encoded?: boolean;
  rawPath?: string;
};

type LambdaResponse = {
  statusCode: number;
  headers: Record<string, string>;
  body: string;
};

function parseRequest(event: LambdaEvent): HttpRequest {
  const method = (event.requestContext?.http?.method ?? "GET").toUpperCase();
  const path = event.rawPath ?? event.requestContext?.http?.path ?? "/";
  const headers: Record<string, string> = {};
  if (event.headers) {
    for (const [k, v] of Object.entries(event.headers)) {
      headers[k.toLowerCase()] = v;
    }
  }
  const query = event.queryStringParameters ?? {};
  const rawBody = event.body;
  const isBase64 = event.isBase64Encoded ?? false;
  let body: string | undefined;
  if (rawBody) {
    body = isBase64 ? Buffer.from(rawBody, "base64").toString("utf-8") : rawBody;
  }
  return { method, path, headers, query, body, rawBody, isBase64Encoded: isBase64 };
}

function toLambdaResponse(res: HttpResponse): LambdaResponse {
  const contentType = res.contentType === "html"
    ? "text/html; charset=utf-8"
    : res.contentType === "text"
      ? "text/plain; charset=utf-8"
      : "application/json";
  const isJson = contentType === "application/json";
  return {
    statusCode: res.status,
    headers: { "Content-Type": contentType, ...res.headers },
    body: isJson && res.body !== undefined ? JSON.stringify(res.body) : String(res.body ?? ""),
  };
}

${hasDeps ? generateDepsRuntime(deps) : ""}
export function createHandler(handler: Handler) {
${hasDeps ? "  let deps: Deps | undefined;\n" : ""}
  return async (event: LambdaEvent): Promise<LambdaResponse> => {
${hasDeps ? "    if (!deps) deps = resolveDeps(); // lazy init on first invocation\n" : ""}
    const req = parseRequest(event);
    const ctx: HandlerContext = { req, ok, fail${hasDeps ? ", ...deps" : ""} };
    try {
      const response = await handler(ctx);
      return toLambdaResponse(response);
    } catch (error) {
      console.error("Handler error:", error);
      return toLambdaResponse(fail("Internal Server Error", 500));
    }
  };
}
`;
};

function generateDepsRuntime(deps: Record<string, string>): string {
  const lines: string[] = [];

  // Check which client types are needed
  const needsTable = Object.values(deps).includes("table");
  const needsBucket = Object.values(deps).includes("bucket");
  const needsQueue = Object.values(deps).includes("fifoQueue");
  const needsMailer = Object.values(deps).includes("mailer");
  const needsWorker = Object.values(deps).includes("worker");

  if (needsTable) {
    lines.push(`
function createTableClient(tableName: string): TableClient {
  const { DynamoDBClient } = require("@aws-sdk/client-dynamodb");
  const { DynamoDBDocumentClient, GetCommand, PutCommand, QueryCommand, DeleteCommand } = require("@aws-sdk/lib-dynamodb");
  const client = DynamoDBDocumentClient.from(new DynamoDBClient({}));
  return {
    async get(pk, sk) {
      const res = await client.send(new GetCommand({ TableName: tableName, Key: { pk, sk } }));
      return (res.Item as Record<string, unknown>) ?? null;
    },
    async put(pk, sk, data) {
      await client.send(new PutCommand({ TableName: tableName, Item: { pk, sk, data } }));
    },
    async query(params) {
      const res = await client.send(new QueryCommand({
        TableName: tableName,
        KeyConditionExpression: params.sk ? "pk = :pk AND sk = :sk" : "pk = :pk",
        ExpressionAttributeValues: { ":pk": params.pk, ...(params.sk ? { ":sk": params.sk } : {}) },
        ...(params.limit ? { Limit: params.limit } : {}),
      }));
      return (res.Items as Record<string, unknown>[]) ?? [];
    },
    async delete(pk, sk) {
      await client.send(new DeleteCommand({ TableName: tableName, Key: { pk, sk } }));
    },
  };
}
`);
  }

  if (needsBucket) {
    lines.push(`
function createBucketClient(bucketName: string): BucketClient {
  const { S3Client, GetObjectCommand, PutObjectCommand, DeleteObjectCommand } = require("@aws-sdk/client-s3");
  const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");
  const s3 = new S3Client({});
  return {
    async get(key) {
      try {
        const res = await s3.send(new GetObjectCommand({ Bucket: bucketName, Key: key }));
        return await res.Body?.transformToString() ?? null;
      } catch { return null; }
    },
    async put(key, body) {
      await s3.send(new PutObjectCommand({ Bucket: bucketName, Key: key, Body: body }));
    },
    async delete(key) {
      await s3.send(new DeleteObjectCommand({ Bucket: bucketName, Key: key }));
    },
    async getSignedUrl(key, expiresIn = 3600) {
      return getSignedUrl(s3, new GetObjectCommand({ Bucket: bucketName, Key: key }), { expiresIn });
    },
  };
}
`);
  }

  if (needsQueue) {
    lines.push(`
function createQueueClient(queueUrl: string): QueueClient {
  const { SQSClient, SendMessageCommand } = require("@aws-sdk/client-sqs");
  const sqs = new SQSClient({});
  return {
    async send(body, groupId, deduplicationId) {
      await sqs.send(new SendMessageCommand({
        QueueUrl: queueUrl,
        MessageBody: JSON.stringify(body),
        ...(groupId ? { MessageGroupId: groupId } : {}),
        ...(deduplicationId ? { MessageDeduplicationId: deduplicationId } : {}),
      }));
    },
  };
}
`);
  }

  if (needsMailer) {
    lines.push(`
function createEmailClient(): EmailClient {
  const { SESv2Client, SendEmailCommand } = require("@aws-sdk/client-sesv2");
  const ses = new SESv2Client({});
  return {
    async send(options) {
      const to = Array.isArray(options.to) ? options.to : [options.to];
      await ses.send(new SendEmailCommand({
        Destination: { ToAddresses: to },
        Content: {
          Simple: {
            Subject: { Data: options.subject },
            Body: {
              ...(options.html ? { Html: { Data: options.html } } : {}),
              ...(options.text ? { Text: { Data: options.text } } : {}),
            },
          },
        },
        ...(options.from ? { FromEmailAddress: options.from } : {}),
      }));
    },
  };
}
`);
  }

  if (needsWorker) {
    lines.push(`
function createWorkerClient(queueUrl: string): WorkerClient {
  const { SQSClient, SendMessageCommand } = require("@aws-sdk/client-sqs");
  const sqs = new SQSClient({});
  return {
    async send(message) {
      await sqs.send(new SendMessageCommand({
        QueueUrl: queueUrl,
        MessageBody: JSON.stringify(message),
      }));
    },
  };
}
`);
  }

  // Generate resolveDeps function
  const depEntries = Object.entries(deps).map(([name, type]) => {
    switch (type) {
      case "table": return `    ${name}: createTableClient(getEnvDep("${name}")),`;
      case "bucket": return `    ${name}: createBucketClient(getEnvDep("${name}")),`;
      case "fifoQueue": return `    ${name}: createQueueClient(getEnvDep("${name}")),`;
      case "mailer": return `    ${name}: createEmailClient(),`;
      case "worker": return `    ${name}: createWorkerClient(getEnvDep("${name}")),`;
      default: return `    ${name}: undefined as any,`;
    }
  });

  lines.push(`
function getEnvDep(name: string): string {
  const raw = process.env[\`EFF_DEP_\${name}\`];
  if (!raw) throw new Error(\`Missing dependency env var: EFF_DEP_\${name}\`);
  // Format: "type:resourceName" — extract the resource name
  const colonIdx = raw.indexOf(":");
  return colonIdx >= 0 ? raw.slice(colonIdx + 1) : raw;
}

function resolveDeps(): Deps {
  return {
${depEntries.join("\n")}
  };
}
`);

  return lines.join("\n");
}
