/**
 * Generates handler.gen.ts for a FIFO Queue message handler — self-contained adapter with
 * all runtime code inlined (zero imports from effortless-aws).
 */

import { generateDepsSection, type GenerateDepsInput } from "./generate-ts-deps";

export type GenerateQueueInput = GenerateDepsInput;

export const generateQueueAdapter = (input: GenerateQueueInput): string => {
  const { deps } = input;
  const hasDeps = Object.keys(deps).length > 0;
  const depsSection = generateDepsSection(deps);

  return `// Auto-generated by effortless-aws. DO NOT EDIT.
// Re-run \`effortless generate\` to regenerate after infra changes.

// ============ Types ============

export type QueueMessage<T = unknown> = {
  body: T;
  messageId: string;
  groupId?: string;
  attributes: Record<string, string>;
};

${depsSection.types}

export type HandlerContext<T = unknown> = {
  message: QueueMessage<T>;
${hasDeps ? Object.keys(deps).map(name => `  ${name}: Deps["${name}"];`).join("\n") : ""}
};

export type Handler<T = unknown> = (ctx: HandlerContext<T>) => Promise<void>;

// ============ Inlined runtime ============

type SQSEvent = {
  Records: Array<{
    messageId: string;
    body: string;
    attributes: Record<string, string>;
    messageAttributes: Record<string, any>;
  }>;
};

type SQSBatchResponse = {
  batchItemFailures: Array<{ itemIdentifier: string }>;
};

${depsSection.runtime}
export function createHandler<T = unknown>(handler: Handler<T>) {
${hasDeps ? "  let deps: Deps | undefined;\n" : ""}
  return async (event: SQSEvent): Promise<SQSBatchResponse> => {
${hasDeps ? "    if (!deps) deps = resolveDeps();\n" : ""}
    const failures: string[] = [];

    for (const record of event.Records) {
      try {
        let body: T;
        try {
          body = JSON.parse(record.body) as T;
        } catch {
          body = record.body as unknown as T;
        }

        const message: QueueMessage<T> = {
          body,
          messageId: record.messageId,
          groupId: record.attributes?.MessageGroupId,
          attributes: record.attributes ?? {},
        };
        const ctx: HandlerContext<T> = { message${hasDeps ? ", ...deps" : ""} };
        await handler(ctx);
      } catch (error) {
        console.error("Queue handler error:", error);
        failures.push(record.messageId);
      }
    }

    return { batchItemFailures: failures.map(id => ({ itemIdentifier: id })) };
  };
}
`;
};
