/**
 * Generates handler.gen.ts for a Cron handler — self-contained adapter with
 * all runtime code inlined (zero imports from effortless-aws).
 */

import { generateDepsSection, type GenerateDepsInput } from "./generate-ts-deps";

export type GenerateCronInput = GenerateDepsInput;

export const generateCronAdapter = (input: GenerateCronInput): string => {
  const { deps } = input;
  const hasDeps = Object.keys(deps).length > 0;
  const depsSection = generateDepsSection(deps);

  return `// Auto-generated by effortless-aws. DO NOT EDIT.
// Re-run \`effortless generate\` to regenerate after infra changes.

${depsSection.types}

export type HandlerContext = {
${hasDeps ? Object.keys(deps).map(name => `  ${name}: Deps["${name}"];`).join("\n") : ""}
};

export type Handler = (ctx: HandlerContext) => Promise<void>;

// ============ Inlined runtime ============

type LambdaEvent = Record<string, unknown>;

${depsSection.runtime}
export function createHandler(handler: Handler) {
${hasDeps ? "  let deps: Deps | undefined;\n" : ""}
  return async (_event: LambdaEvent): Promise<void> => {
${hasDeps ? "    if (!deps) deps = resolveDeps();\n" : ""}
    const ctx: HandlerContext = { ${hasDeps ? "...deps" : ""} };
    try {
      await handler(ctx);
    } catch (error) {
      console.error("Cron handler error:", error);
      throw error;
    }
  };
}
`;
};
