/**
 * Generates handler.gen.ts for a Table Stream handler — self-contained adapter with
 * all runtime code inlined (zero imports from effortless-aws).
 */

import { generateDepsSection, type GenerateDepsInput } from "./generate-ts-deps";

export type GenerateTableStreamInput = GenerateDepsInput;

export const generateTableStreamAdapter = (input: GenerateTableStreamInput): string => {
  const { deps } = input;
  const hasDeps = Object.keys(deps).length > 0;
  const depsSection = generateDepsSection(deps);

  return `// Auto-generated by effortless-aws. DO NOT EDIT.
// Re-run \`effortless generate\` to regenerate after infra changes.

// ============ Types ============

export type TableRecord<T = Record<string, unknown>> = {
  eventName: "INSERT" | "MODIFY" | "REMOVE";
  newImage?: T;
  oldImage?: T;
  keys: Record<string, unknown>;
};

${depsSection.types}

export type HandlerContext<T = Record<string, unknown>> = {
  record: TableRecord<T>;
${hasDeps ? Object.keys(deps).map(name => `  ${name}: Deps["${name}"];`).join("\n") : ""}
};

export type Handler<T = Record<string, unknown>> = (ctx: HandlerContext<T>) => Promise<void>;

// ============ Inlined runtime ============

type DynamoDBStreamEvent = {
  Records: Array<{
    eventName?: string;
    dynamodb?: {
      NewImage?: Record<string, any>;
      OldImage?: Record<string, any>;
      Keys?: Record<string, any>;
    };
  }>;
};

type LambdaResponse = {
  batchItemFailures: Array<{ itemIdentifier: string }>;
};

function unmarshallImage(image: Record<string, any> | undefined): Record<string, unknown> | undefined {
  if (!image) return undefined;
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(image)) {
    if ("S" in value) result[key] = value.S;
    else if ("N" in value) result[key] = Number(value.N);
    else if ("BOOL" in value) result[key] = value.BOOL;
    else if ("NULL" in value) result[key] = null;
    else if ("L" in value) result[key] = value.L;
    else if ("M" in value) result[key] = unmarshallImage(value.M);
    else result[key] = value;
  }
  return result;
}

${depsSection.runtime}
export function createHandler<T = Record<string, unknown>>(handler: Handler<T>) {
${hasDeps ? "  let deps: Deps | undefined;\n" : ""}
  return async (event: DynamoDBStreamEvent): Promise<LambdaResponse> => {
${hasDeps ? "    if (!deps) deps = resolveDeps();\n" : ""}
    const failures: string[] = [];

    for (const record of event.Records) {
      try {
        const tableRecord: TableRecord<T> = {
          eventName: (record.eventName ?? "MODIFY") as "INSERT" | "MODIFY" | "REMOVE",
          newImage: unmarshallImage(record.dynamodb?.NewImage) as T | undefined,
          oldImage: unmarshallImage(record.dynamodb?.OldImage) as T | undefined,
          keys: unmarshallImage(record.dynamodb?.Keys) ?? {},
        };
        const ctx: HandlerContext<T> = { record: tableRecord${hasDeps ? ", ...deps" : ""} };
        await handler(ctx);
      } catch (error) {
        console.error("Table stream handler error:", error);
      }
    }

    return { batchItemFailures: failures.map(id => ({ itemIdentifier: id })) };
  };
}
`;
};
